apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-configmap
  labels:
    app: logstash
data:
  logstash.yml: |-
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
  pipeline.conf: |-
    input {
      beats {
        port => 5044
      }
    }
    output {
      elasticsearch {
        hosts => ['elasticsearch-cluster:9200']
      }
    }
